[package]
name = "game-of-life"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
web-sys = "0.3.77"
wasm-logger = "0.2.0"
log = "0.4.6"
gloo = { version = "0.11.0", features = ["events", "utils"] }